############################
# STAGE 1 execute Golang end to end integration tests
############################
FROM golang:1.12.1-stretch AS tester
ARG APP_URL
ENV GO111MODULE=on

RUN mkdir /slackbot && mkdir /slackbot/TestResults && mkdir /slackbot/TestResults
WORKDIR /slackbot
COPY go.mod .
COPY go.sum .
RUN go mod download build
COPY . .

RUN go get -u github.com/jstemmer/go-junit-report
RUN export APP_URL=${APP_URL}
RUN go test -v ./... -tags e2e_tests | go-junit-report > /slackbot/TestResults/TestReport.xml

############################
# STAGE 2 Upload test results to Azure
############################
FROM microsoft/dotnet:latest AS azcopier
ARG STORAGE_ACCT_URL
ARG STORAGE_ACCT_KEY
ARG BUILD_NUMBER
RUN apt-get update && apt-get -y install rsync --no-install-recommends apt-utils
RUN mkdir /tmp/azcopy && \
    wget -O /tmp/azcopy/azcopy.tar.gz https://aka.ms/downloadazcopyprlinux &&  \
    tar -xf /tmp/azcopy/azcopy.tar.gz -C /tmp/azcopy &&  \
    /tmp/azcopy/install.sh
RUN rm -rf /tmp/azcopy
COPY --from=tester /slackbot/TestResults/TestReport.xml ./TestReport.xml
RUN azcopy \
     --source ./TestReport.xml \
     --destination "${STORAGE_ACCT_URL}/E2E_TestReport_${BUILD_NUMBER}.xml" \
     --dest-key "${STORAGE_ACCT_KEY}"
